// <auto-generated />
namespace QuanLyLinhKienMayTinh.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addngaygiaohangnullableok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addngaygiaohangnullableok));
        
        string IMigrationMetadata.Id
        {
            get { return "201801021748329_add-ngaygiaohang-nullable-ok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
